package cn.hello.bean;

import lombok.Data;

import javax.annotation.sql.DataSourceDefinition;
import java.util.Date;

@Data
public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.id
     *
     * @mbg.generated Thu Apr 18 17:06:26 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.username
     *
     * @mbg.generated Thu Apr 18 17:06:26 CST 2024
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.grade
     *
     * @mbg.generated Thu Apr 18 17:06:26 CST 2024
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.age
     *
     * @mbg.generated Thu Apr 18 17:06:26 CST 2024
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.createtime
     *
     * @mbg.generated Thu Apr 18 17:06:26 CST 2024
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.addr
     *
     * @mbg.generated Thu Apr 18 17:06:26 CST 2024
     */
    private String addr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.id
     *
     * @return the value of tb_student.id
     *
     * @mbg.generated Thu Apr 18 17:06:26 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.id
     *
     * @param id the value for tb_student.id
     *
     * @mbg.generated Thu Apr 18 17:06:26 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.username
     *
     * @return the value of tb_student.username
     *
     * @mbg.generated Thu Apr 18 17:06:26 CST 2024
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.username
     *
     * @param username the value for tb_student.username
     *
     * @mbg.generated Thu Apr 18 17:06:26 CST 2024
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.grade
     *
     * @return the value of tb_student.grade
     *
     * @mbg.generated Thu Apr 18 17:06:26 CST 2024
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.grade
     *
     * @param grade the value for tb_student.grade
     *
     * @mbg.generated Thu Apr 18 17:06:26 CST 2024
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.age
     *
     * @return the value of tb_student.age
     *
     * @mbg.generated Thu Apr 18 17:06:26 CST 2024
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.age
     *
     * @param age the value for tb_student.age
     *
     * @mbg.generated Thu Apr 18 17:06:26 CST 2024
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.createtime
     *
     * @return the value of tb_student.createtime
     *
     * @mbg.generated Thu Apr 18 17:06:26 CST 2024
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.createtime
     *
     * @param createtime the value for tb_student.createtime
     *
     * @mbg.generated Thu Apr 18 17:06:26 CST 2024
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.addr
     *
     * @return the value of tb_student.addr
     *
     * @mbg.generated Thu Apr 18 17:06:26 CST 2024
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.addr
     *
     * @param addr the value for tb_student.addr
     *
     * @mbg.generated Thu Apr 18 17:06:26 CST 2024
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }
}